class_name UiFont
extends RefCounted
## One face for the whole interface, and the three sizes it may be used at.
##
## UI_STYLE.md section 4 asks for two things that have to be decided in one
## place or not at all: a pixel font rather than a scaled ordinary one, and
## monospace on anything with a number in it. A HUD where `ALT 11111` and
## `ALT 88888` are different widths has digits that dance, and a dancing
## number is unreadable however good the rest is.
##
## **What is loaded today is a placeholder.** UI_STYLE already chose the
## real face -- Departure Mono (CC0), with Pixel Operator Mono behind it --
## and neither is in the repository. `resources/ui/pixel_font.tres` is
## generated by `tools/make_font.gd` and stands in until one of them is
## dropped in. Replacing it is replacing that resource and nothing else:
## every screen asks here.
const FACE: String = "res://resources/ui/pixel_font.tres"

## The sizes, and there are two on purpose. A third would be a third
## decision at every call site about which one this is.
##
## **Whole multiples of eight, and nothing else is available.** The face is
## a bitmap at eight pixels with `FIXED_SIZE_SCALE_INTEGER_ONLY`, so asking
## for anything between gets rounded rather than interpolated -- which is
## UI_STYLE's rule about font sizes being multiples of the design size,
## enforced by the font instead of by everyone remembering it.
##
## UI_STYLE lists a third size, 7 px for the diagnostic overlay. It is not
## here because it cannot be: seven is not a multiple of eight. That costs
## nothing, because section 8 of the same document wants the debug overlay
## to look unlike the game, and it keeps its own face.
const BODY: int = 8 ## labels and readings: the bread and butter
const HEADLINE: int = 16 ## a modal heading, or the one number that matters

static var _face: Font = null


## The interface face, loaded once.
##
## Falls back to the engine's own font rather than to nothing, because a
## missing resource must leave the game readable: a HUD with no text at all
## is a worse failure than a HUD in the wrong typeface, and the gallery and
## the tests both have to keep working while the real font is being chosen.
static func face() -> Font:
	if _face == null:
		_face = load(FACE) as Font
	if _face == null:
		push_warning("no interface font at %s; falling back" % FACE)
		_face = ThemeDB.fallback_font
	return _face
